//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietTiecCuoi
    {
        public string ID_TiecCuoi { get; set; }
        public string ID_MonAn { get; set; }
        public string ID_DichVu { get; set; }
        public string GhiChuMA { get; set; }
        public Nullable<int> SLDichVu { get; set; }
    
        public virtual DichVu DichVu { get; set; }
        public virtual MonAn MonAn { get; set; }
        public virtual TiecCuoi TiecCuoi { get; set; }
    }
}
