//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiecCuoi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TiecCuoi()
        {
            this.ChiTietTiecCuois = new HashSet<ChiTietTiecCuoi>();
            this.CTBaoCaoDoanhThus = new HashSet<CTBaoCaoDoanhThu>();
        }
    
        public string Ngay { get; set; }
        public string Ca { get; set; }
        public string ID_Sanh { get; set; }
        public string TienDatCoc { get; set; }
        public string SobanDuTru { get; set; }
        public string ID_KhachHang { get; set; }
        public string ID_TiecCuoi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietTiecCuoi> ChiTietTiecCuois { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTBaoCaoDoanhThu> CTBaoCaoDoanhThus { get; set; }
        public virtual HoaDon HoaDon { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual Sanh Sanh { get; set; }
    }
}
