//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIECCUOI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIECCUOI()
        {
            this.CTBaoCaoDS = new HashSet<CTBaoCaoD>();
        }
    
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<int> Ca { get; set; }
        public string ID_Sanh { get; set; }
        public Nullable<double> TienDatCoc { get; set; }
        public Nullable<int> SobanDuTru { get; set; }
        public string ID_KhachHang { get; set; }
        public int ID_TiecCuoi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTBaoCaoD> CTBaoCaoDS { get; set; }
        public virtual CTTiecCuoi CTTiecCuoi { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual SANH SANH { get; set; }
    }
}
